FROM node:alpine as build
WORKDIR /usr/src/app
COPY . /usr/src/app/
RUN npm install -g @angular/cli@18
RUN npm install
RUN ng build --prod

FROM nginx:alpine
COPY --from=build /usr/src/app/dist/mcda-frontend /usr/share/nginx/html
COPY nginx.conf /etc/nginx/nginx.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
