services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: mcda-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - SELENIUM_ENV=docker
    depends_on:
      - db
      - selenium

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: mcda-frontend
    ports:
      - "4200:4200"
    depends_on:
      - backend

  db:
    image: postgres:13
    container_name: mcda-db
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  selenium:
    image: seleniarm/standalone-chromium
    container_name: mcda-selenium
    ports:
      - "4444:4444"
    shm_size: 1gb 

volumes:
  postgres_data: