FROM python:3.12-slim
WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . . 

ENV PYTHONUNBUFFERED 1
EXPOSE 8000

COPY backend_prod.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/backend_prod.sh

CMD ["/usr/local/bin/backend_prod.sh"]